"""Agent 4 — Humanization Engine: makes content sound naturally human.

v2.0 — Aggressive false negative removal + deterministic cleanup pass.
"""
import uuid
import logging
from services.llm import complete
from services.text_cleaner import clean_ai_patterns, detect_all_patterns, detect_false_negatives

from typing import TypedDict

log = logging.getLogger("ai-engine.humanizer")

# ✅ FIX: Lazy initialization — module import pe crash nahi hoga
_rule_engine = None

def _get_rule_engine():
    """Lazy-load Rule Engine — only when first needed."""
    global _rule_engine
    if _rule_engine is None:
        try:
            from agents.rule_engine.orchestrator import RuleEngineOrchestrator
            _rule_engine = RuleEngineOrchestrator()
            log.info("Rule Engine initialized successfully")
        except Exception as e:
            log.error("Rule Engine initialization failed: %s", e)
            raise
    return _rule_engine


class IntensityRuleConfig(TypedDict):
    description: str
    rules: list[str]
    temperature: float
    second_pass: bool


SYSTEM = """You are a master editor who transforms AI-generated content into naturally human prose.

CORE MISSION:
Make content feel like it was written by a thoughtful, experienced professional —
not generated by AI. Preserve all facts, data, and strategic meaning.
Never fabricate information, statistics, or anecdotes.

═══════════════════════════════════════════════════════════════
CRITICAL RULE — FALSE NEGATIVES ARE FORBIDDEN
═══════════════════════════════════════════════════════════════

A "false negative" is when you say what something is NOT, only to then say what it IS.
This is the #1 dead giveaway of AI writing. ELIMINATE all instances.

❌ FORBIDDEN PATTERNS — never use these:

  "It's not just X, it's Y"
  "This isn't just about X, it's about Y"
  "It's not merely X, it's Y"
  "Not only does it X, but it also Y"
  "This is more than just X"
  "Rather than being X, it's Y"
  "Far from being X, it's Y"
  "This isn't your typical X"
  "It's less about X and more about Y"
  "Not a X, but a Y"

✅ INSTEAD — state the positive claim directly:

  BAD:  "Blockchain isn't just about crypto, it's about trust."
  GOOD: "Blockchain builds trust through cryptography."

  BAD:  "This isn't just a trend, it's a revolution."
  GOOD: "This is a revolution."

  BAD:  "Not only does it scale, but it also secures."
  GOOD: "It scales and secures."

  BAD:  "It's more than just a feature — it's a strategy."
  GOOD: "This feature drives the strategy."

RULE: If you catch yourself writing "not just", "not merely", "not only",
"isn't just", "more than just", "not about X, about Y" — STOP and rewrite
as a direct assertion.
"""

# ─── AI Phrase Blacklist ──────────────────────────────────────────────────────

BANNED_AI_PHRASES = [
    # False negatives (HIGHEST PRIORITY)
    "It's not just",
    "This isn't just",
    "It's not merely",
    "It's not only",
    "Not only",
    "More than just",
    "Far from being",
    "Rather than being",
    "Isn't your typical",
    "Less about",
    "It's not about",

    # Opening clichés
    "In today's fast-paced world",
    "In today's rapidly evolving",
    "In an era of",
    "In the age of",
    "In the realm of",
    "In the world of",
    "In the landscape of",
    "It is important to note",
    "It's worth noting that",
    "It goes without saying",
    "Needless to say",
    "When it comes to",
    "At its core",
    "At the heart of",

    # Transitions
    "In conclusion",
    "To summarize",
    "To recap",
    "In summary",
    "As we can see",
    "As mentioned above",
    "As previously discussed",
    "Furthermore",
    "Moreover",
    "Additionally",
    "In addition to this",
    "Consequently",
    "That being said",
    "With that in mind",

    # Corporate buzzwords
    "Game-changing",
    "Groundbreaking",
    "Revolutionary",
    "Transformative",
    "Disruptive",
    "Unprecedented",
    "Paradigm shift",
    "Synergy",
    "Ecosystem",
    "Leverage",
    "Utilize",
    "Operationalize",
    "Empower",
    "Facilitate",
    "Circle back",
    "Touch base",
    "Move the needle",
    "Low-hanging fruit",
    "Boil the ocean",
    "Peel back the layers",
    "Unpack",
    "Double-click on",
    "Dive deep",
    "Deep dive",

    # AI tells
    "Robust",
    "Seamless",
    "Holistic",
    "Cutting-edge",
    "State-of-the-art",
    "Best-in-class",
    "World-class",
    "Best practices",
    "Delve into",
    "Nuanced understanding",
    "Comprehensive overview",
    "Tapestry",
    "At the end of the day",
    "The reality is",
    "It's no secret that",
    "Navigate the complexities",
    "Unlock the power",
    "Harness the power",

    # Enthusiasm tells
    "Excited to share",
    "Thrilled to announce",
    "Delighted to present",
    "I am pleased to",
    "We are excited to",
]


# ─── Intensity Instructions ───────────────────────────────────────────────────

INTENSITY_RULES: dict[str, IntensityRuleConfig] = {
    "light": {
        "description": "Minimal changes — surgical removal of AI tells only.",
        "rules": [
            "Remove ONLY the most obvious AI clichés from the banned list",
            "Eliminate ALL false negatives (not just/not merely/not only patterns)",
            "Keep sentence structure and rhythm largely intact",
            "Preserve all formatting, headings, and paragraph breaks",
            "Do NOT restructure — only spot-fix robotic phrases",
        ],
        "temperature": 0.5,
        "second_pass": False,
    },
    "medium": {
        "description": "Balanced humanization — natural flow with preserved structure.",
        "rules": [
            "Remove ALL banned AI phrases — replace with natural, specific alternatives",
            "ELIMINATE every false negative — convert to direct positive assertions",
            "Vary sentence lengths — mix short (5-8 words) with longer ones",
            "Add subtle rhythm variation — not every paragraph the same length",
            "Use contractions naturally (it's, you'll, we're) — but not forced",
            "Replace generic adjectives with specific, concrete ones",
            "Occasional conversational aside is fine (e.g., 'Here's the thing:')",
            "Maintain professional tone throughout",
            "Do not add fabricated details",
        ],
        "temperature": 0.65,
        "second_pass": True,
    },
    "aggressive": {
        "description": "Maximum humanization — rewrite for authentic human voice.",
        "rules": [
            "Substantially rewrite for naturalness — don't just swap phrases",
            "ZERO tolerance for false negatives — every 'not just X, it's Y' must become direct assertion",
            "Dramatically vary sentence lengths and structures throughout",
            "Break some grammar rules intentionally for voice (fragments are fine)",
            "Add micro-observations or brief qualifiers (e.g., 'at least in my experience')",
            "Use casual asides sparingly: 'honestly,' 'look,' 'here's the thing'",
            "Mix active and passive voice naturally — don't force everything active",
            "End thoughts abruptly sometimes — humans trail off",
            "Remove ALL corporate enthusiasm — no 'excited to share' etc.",
            "Replace 'A is B' reductive statements with nuanced phrasing",
            "Cut all filler openers and transitions — just jump to the point",
            "Result should feel like a thoughtful person wrote it from scratch",
        ],
        "temperature": 0.72,
        "second_pass": True,
    },
}

# ─── Language-Specific Rules ──────────────────────────────────────────────────

LANGUAGE_RULES = {
    "Hindi": (
        "Apply humanization rules while writing in Hindi. "
        "Use natural Hindi idioms and phrasing. "
        "Avoid direct English translations."
    ),
    "Hinglish": (
        "Content is in Hinglish (Hindi-English mix). "
        "Humanize in a way that feels natural to Indian professionals — "
        "casual Hindi expressions mixed with English are expected and welcome."
    ),
    "Spanish": (
        "Apply humanization in Spanish. "
        "Use natural Spanish phrasing and avoid direct translations from English."
    ),
    "French": "Apply humanization in French. Use natural French phrasing.",
}

# ─── Tonality Integration ─────────────────────────────────────────────────────

TONALITY_HUMANIZE_RULES = {
    "angry":      "Let measured indignation show through word choice — sharp edges, not explosive.",
    "frustrated": "Slight exasperation in sentence rhythm — shorter, more clipped phrasing.",
    "excited":    "Genuine energy — varied punctuation, some short punchy sentences.",
    "confident":  "Declarative statements — minimal hedging, direct assertions.",
    "curious":    "Questions and wondering — invite the reader to think alongside you.",
    "empathetic": "Warmer language — 'I understand...', 'Many of us have...'",
    "playful":    "Light wordplay, the occasional unexpected word choice.",
    "serious":    "Measured pacing, weighty words — no lightness or humor.",
}

# ─── Prompt Template ──────────────────────────────────────────────────────────

USER_TEMPLATE = """Humanize the following content.

CONTENT:
{content}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HUMANIZATION INTENSITY: {intensity_upper}
{description}

RULES TO APPLY:
{rules_block}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{detection_block}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BANNED AI PHRASES — eliminate every instance:
{banned_block}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{tonality_block}
{language_block}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ABSOLUTE RULES:
- Keep ALL facts, statistics, names, and data exactly as they are
- Do NOT add invented anecdotes, statistics, or claims
- Do NOT reduce total content length by more than 10%
- Preserve the overall structure (headings, sections, key points)
- CRITICAL: Zero false negatives — no "not just X, it's Y" patterns

OUTPUT: Write only the humanized content. No commentary, no labels."""


# ─── Second Pass Prompt ───────────────────────────────────────────────────────

SECOND_PASS_SYSTEM = """You are a final-pass editor whose sole job is to eliminate FALSE NEGATIVES.

A false negative is any construction like:
  - "not just X, it's Y"
  - "isn't merely X, it's Y"
  - "not only X, but also Y"
  - "more than just X"
  - "not about X, it's about Y"

These are AI writing tells. Convert every one into a DIRECT ASSERTION.

Examples of fixes:
  BAD:  "Blockchain isn't just about crypto — it's about trust."
  GOOD: "Blockchain enables trust. Crypto is one application." ✅

  BAD:  "Not only does it scale, but it also secures."
  GOOD: "It scales and secures." ✅

  BAD:  "This is more than just a product."
  GOOD: "This product changes how you work." ✅

RULES:
1. Keep all facts, data, structure, and formatting intact
2. Only rewrite sentences containing false negatives
3. Preserve length within 5%
4. Output only the fixed content — no commentary
"""

# ─── Detection Block Builder ──────────────────────────────────────────────────

def _build_detection_block(content: str) -> str:
    """Build detection warnings for LLM based on actual patterns found."""
    detections = detect_all_patterns(content)

    if detections["total_issues"] == 0:
        return "PRE-SCAN: No obvious AI patterns detected. Focus on natural voice."

    lines = ["🚨 PRE-SCAN DETECTED THESE ISSUES — FIX ALL OF THEM:"]

    if detections["false_negative_count"] > 0:
        false_negs = detect_false_negatives(content)
        examples   = [f"'{f['match']}'" for f in false_negs[:3]]
        lines.append(
            f"  ⚠️  FALSE NEGATIVES ({detections['false_negative_count']} found): "
            f"{', '.join(examples)}"
        )
        lines.append("     → Convert each to a direct positive assertion.")

    if detections["ai_openings"] > 0:
        lines.append(f"  ⚠️  AI OPENING CLICHES ({detections['ai_openings']} found)")
        lines.append("     → Start with a specific observation, not 'In today's world...'")

    if detections["hedging"] > 0:
        lines.append(f"  ⚠️  HEDGING PHRASES ({detections['hedging']} found)")
        lines.append("     → State things directly. Delete 'It's worth noting...'")

    if detections["buzzwords"] > 0:
        lines.append(f"  ⚠️  BUZZWORDS ({detections['buzzwords']} found)")
        lines.append("     → Replace with simple, specific words.")

    if detections["transitions"] > 0:
        lines.append(f"  ⚠️  AI TRANSITIONS ({detections['transitions']} found)")
        lines.append("     → Use natural connectors: 'But', 'So', 'And', 'Still'")

    return "\n".join(lines)


# ─── Agent Entry Point ────────────────────────────────────────────────────────

async def run(
    content:       str,
    intensity:     str       = "medium",
    tonality:      dict | None = None,
    language:      str       = "English",
    brand_phrases: list | None = None,
    user_prompt:   str       = "",
    brand_data:    dict | None = None,
    extra_context: dict | None = None,
    request_id:    str | None  = None,
) -> dict:
    """
    Humanize content with aggressive false negative removal + Rule Engine pass.
    """
    import traceback as _tb

    # ── Input validation ──────────────────────────────────────────────────────
    if not content or not isinstance(content, str):
        log.error("Humanizer received invalid content: type=%s", type(content))
        return {
            "content":    str(content) if content else "",  # noqa
            "tokensUsed": 0,
            "agent":      "humanizer",
            "intensity":  intensity,
            "metadata":   {"error": "invalid_input", "rule_engine": {"enabled": False}},
        }

    # ── Validate intensity ────────────────────────────────────────────────────
    if intensity not in INTENSITY_RULES:
        log.warning("Invalid intensity '%s' — defaulting to medium", intensity)
        intensity = "medium"

    rules_config       = INTENSITY_RULES[intensity]
    rules_list         = rules_config["rules"]
    temp_val           = rules_config["temperature"]
    second_pass_enabled = rules_config["second_pass"]

    # ── Pre-scan (safe) ───────────────────────────────────────────────────────
    try:
        pre_detections = detect_all_patterns(content)
        detection_block = _build_detection_block(content)
    except Exception as e:
        log.warning("Pre-scan failed, continuing: %s", e)
        pre_detections = {"total_issues": 0, "false_negative_count": 0,
                          "ai_openings": 0, "hedging": 0, "buzzwords": 0, "transitions": 0}
        detection_block = "PRE-SCAN: Skipped due to error."

    # ── Banned phrases ────────────────────────────────────────────────────────
    all_banned = list(BANNED_AI_PHRASES)
    if brand_phrases:
        for phrase in brand_phrases:
            if phrase and phrase not in all_banned:
                all_banned.append(phrase)

    banned_block = "\n".join(f"  • {p}" for p in all_banned)
    rules_block  = "\n".join(f"  {i+1}. {r}" for i, r in enumerate(rules_list))

    # ── Tonality block ────────────────────────────────────────────────────────
    tonality_lines = []
    if tonality and isinstance(tonality, dict):
        try:
            active = [
                (k, v) for k, v in tonality.items()
                if isinstance(v, (int, float)) and v >= 5 and k in TONALITY_HUMANIZE_RULES
            ]
            active.sort(key=lambda x: x[1], reverse=True)
            if active:
                tonality_lines.append("TONALITY TO REFLECT IN HUMANIZATION:")
                for tone, val in active[:4]:
                    rule = TONALITY_HUMANIZE_RULES[tone]
                    tonality_lines.append(f"  • {tone.upper()} ({val}/10): {rule}")
        except Exception as e:
            log.warning("Tonality processing failed: %s", e)

    tonality_block = "\n".join(tonality_lines) if tonality_lines else ""

    # ── Language block ────────────────────────────────────────────────────────
    lang_instruction = LANGUAGE_RULES.get(language, "")
    language_block   = (
        f"LANGUAGE NOTE: {lang_instruction}"
        if lang_instruction
        else f"Language: {language} — apply all rules in this language."
    )

    # ── Token budget ──────────────────────────────────────────────────────────
    content_words = len(content.split())
    max_tok = min(int(content_words * 1.5) + 600, 6000)

    log.info(
        "Humanizer start | intensity=%s | words=%d | lang=%s | pre_issues=%d",
        intensity, content_words, language, pre_detections["total_issues"],
    )

    # ── Pass 1: LLM Humanization ──────────────────────────────────────────────
    try:
        user_prompt_text = USER_TEMPLATE.format(
            content=content,
            intensity_upper=intensity.upper(),
            description=f"Goal: {rules_config['description']}",
            rules_block=rules_block,
            detection_block=detection_block,
            banned_block=banned_block,
            tonality_block=tonality_block,
            language_block=language_block,
        )

        humanized, tokens_p1 = await complete(
            SYSTEM,
            user_prompt_text,
            temperature=temp_val,
            max_tokens=max_tok,
        )
    except Exception as e:
        log.error("Humanizer LLM call FAILED: %s\n%s", e, _tb.format_exc())
        # Fallback: return original content
        return {
            "content":    content,
            "tokensUsed": 0,
            "agent":      "humanizer",
            "intensity":  intensity,
            "metadata": {
                "error": f"llm_failed: {type(e).__name__}: {str(e)[:200]}",
                "rule_engine": {"enabled": False, "reason": "humanizer_llm_failed"},
            },
        }

    if not humanized or not isinstance(humanized, str):
        log.error("Humanizer LLM returned empty/invalid content")
        return {
            "content":    content,
            "tokensUsed": tokens_p1,
            "agent":      "humanizer",
            "intensity":  intensity,
            "metadata": {"error": "empty_llm_response",
                         "rule_engine": {"enabled": False}},
        }

    total_tokens = tokens_p1

    # ── Pass 2: Deterministic Cleanup ─────────────────────────────────────────
    try:
        cleanup_result = clean_ai_patterns(humanized, intensity=intensity)
        humanized      = cleanup_result["content"]
    except Exception as e:
        log.warning("Cleanup pass failed, continuing: %s", e)
        cleanup_result = {"content": humanized, "detections": {"before": {}, "after": {}}}

    # ── Pass 3: Second LLM Pass (only if false negatives remain) ─────────────
    tokens_p2       = 0
    second_pass_run = False

    try:
        post_scan = detect_false_negatives(humanized)

        if second_pass_enabled and len(post_scan) > 0:
            log.info("Second pass triggered | remaining_false_negs=%d", len(post_scan))
            second_pass_run = True

            second_pass_user = (
                f"The text below still contains {len(post_scan)} false negative(s).\n\n"
                f"DETECTED PATTERNS TO FIX:\n"
                + "\n".join(f"  - '{f['match']}'" for f in post_scan[:5])
                + f"\n\nRewrite ONLY the sentences containing these patterns.\n"
                f"Convert each to a direct positive assertion.\n"
                f"Keep everything else unchanged.\n\n"
                f"TEXT:\n{humanized}\n\nOutput only the fixed text."
            )

            humanized_p2, tokens_p2 = await complete(
                SECOND_PASS_SYSTEM,
                second_pass_user,
                temperature=0.5,
                max_tokens=max_tok,
            )

            if humanized_p2 and isinstance(humanized_p2, str):
                p2_scan = detect_false_negatives(humanized_p2)
                if len(p2_scan) < len(post_scan):
                    humanized = humanized_p2
                    try:
                        cleanup_result2 = clean_ai_patterns(humanized, intensity=intensity)
                        humanized = cleanup_result2["content"]
                    except Exception as e:
                        log.warning("Second cleanup pass failed: %s", e)
                else:
                    log.warning("Second pass did not improve — using first pass result")

            total_tokens += tokens_p2
    except Exception as e:
        log.warning("Second pass failed, using first pass result: %s", e)

    # ── Rule Engine (isolated failure + skip flag) ──────────────────────────
    rule_engine_meta: dict = {"enabled": False}

    # ✅ Check if rule engine should be skipped (for fast rehumanize)
    skip_rule_engine = bool(
        (extra_context or {}).get("skip_rule_engine", False)
    )

    if skip_rule_engine:
        log.info("Rule Engine SKIPPED (fast mode requested)")
        rule_engine_meta = {"enabled": False, "reason": "skipped_by_request"}
    else:
        try:
            req_id = request_id or str(uuid.uuid4())
            engine = _get_rule_engine()
            safe_brand_data = brand_data or {}

            re_result = await engine.process(
                content=humanized,
                user_prompt=user_prompt or content[:200],
                brand_data=safe_brand_data,
                extra_context=extra_context,
                request_id=req_id,
            )

            # Only use Rule Engine output if it succeeded
            if re_result and hasattr(re_result, 'final_content') and re_result.final_content:
                humanized = re_result.final_content

                static_val         = re_result.static_validation
                static_score       = static_val.static_score  if static_val else 0.0
                dynamic_score      = static_val.dynamic_score if static_val else 0.0
                passed             = static_val.passed        if static_val else False
                violations_count   = len(static_val.violations)      if static_val else 0
                category_breakdown = static_val.category_breakdown if static_val else {}

                rule_engine_meta = {
                    "enabled":                    True,
                    "final_score":                re_result.final_score,
                    "static_score":               static_score,
                    "dynamic_score":              dynamic_score,
                    "passed":                     passed,
                    "total_iterations":           re_result.total_iterations,
                    "false_negatives_eliminated": re_result.false_negatives_eliminated,
                    "dynamic_rules_generated":    len(re_result.dynamic_rules.rules),
                    "violations_remaining":       violations_count,
                    "category_breakdown":         category_breakdown,
                    "improvement_log":            re_result.improvement_log,
                    "processing_ms":              re_result.processing_time_ms,
                }

                log.info(
                    "Rule Engine complete | score=%.1f%% | passed=%s | iterations=%d",
                    re_result.final_score, passed, re_result.total_iterations,
                )
            else:
                log.warning("Rule Engine returned empty result — skipping")
                rule_engine_meta = {"enabled": True, "skipped": "empty_result"}

        except Exception as e:
            log.error("Rule Engine FAILED (non-fatal): %s\n%s", e, _tb.format_exc())
            rule_engine_meta = {
                "enabled": True,
                "error": f"{type(e).__name__}: {str(e)[:200]}",
            }

    # ── Final metrics (safe) ──────────────────────────────────────────────────
    try:
        final_detections = detect_all_patterns(humanized)
        pre_total  = pre_detections["total_issues"]
        post_total = final_detections["total_issues"]
        reduction_pct = round(
            ((pre_total - post_total) / pre_total * 100)
            if pre_total > 0 else 100.0, 1,
        )
    except Exception as e:
        log.warning("Final metrics failed: %s", e)
        final_detections = {"total_issues": 0, "false_negative_count": 0}
        pre_total, post_total, reduction_pct = 0, 0, 0

    log.info(
        "Humanizer complete | intensity=%s | tokens=%d (p1=%d, p2=%d) | reduction=%.1f%%",
        intensity, total_tokens, tokens_p1, tokens_p2, reduction_pct,
    )

    cleanup_detections: dict = cleanup_result.get("detections", {}) if isinstance(cleanup_result.get("detections"), dict) else {}

    return {
        "content":    humanized,
        "tokensUsed": total_tokens,
        "agent":      "humanizer",
        "intensity":  intensity,
        "metadata": {
            "pre_issues":           pre_total,
            "post_issues":          post_total,
            "reduction_percent":    reduction_pct,
            "false_negatives_pre":  pre_detections.get("false_negative_count", 0),
            "false_negatives_post": final_detections.get("false_negative_count", 0),
            "second_pass_run":      second_pass_run,
            "detections_before":    cleanup_detections.get("before", {}),
            "detections_after":     cleanup_detections.get("after", {}),
            "rule_engine":          rule_engine_meta,
        },
    }